trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '22.x'

- script: |
    npm install
    npm run build
  displayName: Build

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Service principal (manual)'
    appType: 'webAppLinux'
    appName: 'portfolio-be'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'